swagger: "2.0"
info:
  version: "0.0.1"
  title: API Gateway
host: localhost:8080
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /swagger:
    x-swagger-pipe: swagger_raw
  /ka:
    x-swagger-router-controller: keep_alive
    get:
      description: If all is fine it returns OK
      operationId: keepAlive
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/KeepAlive_Response"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Standard_ErrorResponse"


definitions:
  # Keep Alive
  KeepAlive_Response:
    required:
      - status
    properties:
      status:
        type: string

  # Shared definitions
  Standard_ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string