version: '3.2'
services: 
  webapp:
    build: ./WebApp
    ports:
      - "5050:80"
#  mobileapp:
#    build: ./MobileApp
#    links: 
#      - rabbitmq_ext
#      - apigateway
  rabbitmq_ext:
    build: ./ExtRabbit
    ports:
      - "15672:15672"
      - "15675:15675"
      - "5672:5672"
  apigateway:
    build: ./APIGateway
    ports: 
      - 8080:8080
    links: 
      - rabbitmq_int
      - rabbitmq_ext
  apiportal:
    build: ./APIPortal
    ports:
      - "6060:80"
  apiportalbackend:
    build: ./APIPortalBackend
    links: 
      - rabbitmq_int
    ports:
      - "7070:7070"
  rabbitmq_int:
    image: rabbitmq:management-alpine
    ports:
      - "25672:15672"
      - "6672:5672"
  microbusiness:
    build: ./MicroBusiness
    links:
      - rabbitmq_int
      - rabbitmq_ext
  mongodb:
    image: "mongo"