export const API_DEFS_FETCHED = 'API_DEFS_FETCHED'
export const API_FETCH_FAILED = 'API_FETCH_FAILED'
export const API_DEFS_STORED = 'API_DEFS_STORED'
export const API_STORE_FAILED = 'API_STORE_FAILED'
